export type SkillGroup = {
  id: string;
  label: string;
  hue: string;
  items: string[];
};

/**
 * Skill groupings mirror the resume. Cybersecurity is intentionally last
 * (data + AI + engineering lead the framing).
 */
export const skillGroups: SkillGroup[] = [
  {
    id: "languages",
    label: "Languages",
    hue: "var(--color-text-0)",
    items: [
      "Python",
      "C",
      "SQL",
      "Java",
      "JavaScript",
      "TypeScript",
      "HTML",
      "CSS",
      "R (basic)",
    ],
  },
  {
    id: "ml-ai",
    label: "Machine Learning & AI",
    hue: "var(--color-accent)",
    items: [
      "scikit-learn (sklearn)",
      "XGBoost",
      "LightGBM",
      "Gradient Boosting",
      "ARIMA",
      "Time-Series Forecasting",
      "Predictive Modeling",
      "Feature Engineering",
      "Cross-Validation",
      "Hyperparameter Tuning",
      "Model Evaluation",
    ],
  },
  {
    id: "genai-llm",
    label: "Generative AI & LLM",
    hue: "var(--color-accent-3)",
    items: [
      "Large Language Models (LLM)",
      "LangChain",
      "Retrieval-Augmented Generation (RAG)",
      "Prompt Engineering",
      "Llama 3.3",
      "Groq",
      "OpenAI API",
      "Document Extraction",
      "Conversational AI",
    ],
  },
  {
    id: "data-eng",
    label: "Data Engineering",
    hue: "var(--color-accent-2)",
    items: [
      "Pandas",
      "NumPy",
      "ETL Pipelines",
      "Data Cleaning",
      "Data Validation",
      "Exploratory Data Analysis (EDA)",
      "Data Mining",
    ],
  },
  {
    id: "databases",
    label: "Databases & Storage",
    hue: "var(--color-accent-2)",
    items: [
      "PostgreSQL",
      "BigQuery",
      "Supabase (Postgres)",
      "MySQL",
      "SQLite",
    ],
  },
  {
    id: "viz",
    label: "Visualisation & BI",
    hue: "var(--color-accent-3)",
    items: [
      "Apache ECharts",
      "Power BI",
      "Tableau",
      "Excel (VBA, Advanced Formulas)",
      "Data Storytelling",
      "Interactive Dashboards",
      "Streamlit",
    ],
  },
  {
    id: "web",
    label: "Web & Backend",
    hue: "var(--color-accent)",
    items: [
      "Flask",
      "Django",
      "FastAPI",
      "Vue.js",
      "React",
      "Vite",
      "Tailwind CSS",
      "shadcn/ui",
      "Babylon.js",
      "Supabase",
      "REST APIs",
      "Mobile App Development",
      "WebXR",
      "Next.js",
    ],
  },
  {
    id: "gis-cloud",
    label: "GIS & Cloud",
    hue: "var(--color-accent-2)",
    items: [
      "ArcGIS",
      "Geospatial Data",
      "Geospatial Analytics",
      "Google Cloud Platform (GCP)",
      "AWS (basic)",
      "Linux / Unix",
    ],
  },
  {
    id: "automation",
    label: "Automation & Tools",
    hue: "var(--color-accent-3)",
    items: [
      "UiPath (RPA)",
      "Robotic Process Automation",
      "Python Scripting",
      "KNIME",
      "Git",
      "Workflow Automation",
      "GitHub Actions",
      "pytest",
    ],
  },
  {
    id: "methods",
    label: "Methods & Practices",
    hue: "var(--color-text-1)",
    items: [
      "Agile / Scrum",
      "Stakeholder Management",
      "Data Storytelling",
      "Risk & Governance",
      "Cross Functional Collaboration",
      "Technical Documentation",
      "CI/CD",
    ],
  },
  {
    id: "security",
    label: "Cybersecurity",
    hue: "var(--color-accent)",
    items: [
      "Security Operations Center (SOC)",
      "Threat Hunting",
      "Incident Response",
      "Digital Forensics",
      "Computer Forensics",
      "Compliance Enforcement",
      "SIEM",
    ],
  },
];
