export type SkillGroup = {
  id: string;
  label: string;
  hue: string;
  items: string[];
};

export const skillGroups: SkillGroup[] = [
  {
    id: "ai",
    label: "GenAI & ML",
    hue: "var(--color-accent)",
    items: [
      "LLM Application Development",
      "Llama 3.3",
      "Groq",
      "LangChain",
      "RAG Pipelines",
      "Prompt Engineering",
      "Agentic Workflows",
      "scikit-learn",
      "XGBoost",
      "LightGBM",
      "Time-Series Forecasting",
      "ARIMA",
      "Feature Engineering",
      "Model Evaluation",
      "Cross-Validation",
    ],
  },
  {
    id: "data",
    label: "Data & Analytics",
    hue: "var(--color-accent-2)",
    items: [
      "Python (pandas, NumPy)",
      "SQL (PostgreSQL, BigQuery)",
      "Data Cleaning",
      "EDA",
      "ETL Pipelines",
      "Predictive Modeling",
      "Apache ECharts",
      "Power BI",
      "Tableau",
      "ArcGIS",
      "Geospatial Analytics",
    ],
  },
  {
    id: "engineering",
    label: "Engineering & Systems",
    hue: "var(--color-accent-3)",
    items: [
      "Python",
      "TypeScript",
      "React",
      "Vue.js",
      "Next.js",
      "Flask",
      "Django",
      "FastAPI",
      "RESTful APIs",
      "Supabase",
      "Babylon.js",
      "WebXR",
      "Google Cloud Platform",
      "UiPath Automation",
      "Git",
      "Linux / Unix",
    ],
  },
  {
    id: "professional",
    label: "Professional",
    hue: "var(--color-text-1)",
    items: [
      "Agile / Sprint-Based Dev",
      "Cross-Functional Collaboration",
      "Technical Documentation",
      "Requirements Translation",
      "Structured Problem-Solving",
      "Clear Technical Communication",
      "High-Pressure Adaptability",
    ],
  },
  {
    id: "security",
    label: "Cybersecurity & Ops",
    hue: "var(--color-accent)",
    items: [
      "SIEM",
      "DFIR",
      "Threat Hunting",
      "Phishing Remediation",
      "CCTV Analytics",
      "Facial Recognition",
      "Security & Governance",
      "Excel (VBA)",
      "KNIME",
    ],
  },
];
